apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-second-pod
  name: my-second-pod
spec:
  containers:
  - image: nginx
    name: my-second-pod
    resources: {}
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
