apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-second-pod
  name: mypod-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30250
  selector:
    run: my-second-pod
status:
  loadBalancer: {}
