apiVersion: v1
kind: Service   
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort 
  ports:
  - nodePort: 30001
    port: 3000        
    targetPort: 80
  selector:
    env: front-end